### PR TITLE
Enable AP mode

### PR DESCRIPTION
**Pull request by EduSSantoz**
AP mode is fully working only thing that was found remaining was to enable it.
Fully tested and working fine.

### CODE REVIEW

**Comment by k3a** [comment]
Hi, have you considered upstreaming it? It is strange that in-tree module still mentiones STA only...

**Comment by EduSSantoz** [comment]
i don't know how to do it but already put a request, it need some manteiner attention.

**Comment by k3a** [comment]
I know how to do it, I have done it once. There is a [long guide](https://www.kernel.org/doc/html/latest/process/submitting-patches.html). In short, you need to look up maintainers in MAINTAINERS file in the linux source root. 

For mt7601u it is:
```
M:  Jakub Kicinski <kubakici (AT-SYMBOL-NO-SPAM) wp.pl>
L:  linux-wireless (AT-SYMBOL-NO-SPAM) vger.kernel.org
S:  Maintained
F:  drivers/net/wireless/mediatek/mt7601u/
```

Then you could theoretically contact Jakub and ask him to do that but probably better way is don't disturb him and instead create a proper patchfile and send it to linux-wireless (AT-SYMBOL-NO-SPAM)  vger.kernel.org. In the long guide I mentioned there are some requirements which MUST be met for patch to be accepted - avoid long lines, make it clear, ideally a single patch, must include Signed-off-by header, etc. Requirements are described in the guide.

After a well-formated patch is sent to the list email, the patch will be visible at [patchwork](https://patchwork.kernel.org/project/linux-wireless/list/?series=&submitter=&state=&q=mt7601u&archive=&delegate=) site. Then maintainers can review it and decide to merge upstream. In this case, maybe Jakub can "ack" it automatically by just responding to the patch email (not sure).

If you want, I can try to do that myself. Or you can try to follow this mailings list procedure. :)
It is strange that no one has enabled those AP bits yet, especially as Jakub is alive and [responding](https://patchwork.kernel.org/project/linux-wireless/patch/20210225183241.1002129-1-colin.king@canonical.com/). Do you think there is something more missing preventing the AP from working? I tested your fork briefly and it appeared to be working normally.

**Comment by EduSSantoz** [comment]
I never have did that before and i know theres such a monarchy on linux development to ensure nothing bad/evil/wrong goes in the kernel.

the guides makes it even more of a nightmare/headache to submit the patch, at least doesn't makes me happy to contribute with.

that would be nice if you can do that for me.

i have a bunch of those cards and needed to create a ap with it on linux as on windows it works well,
the problem must be on driver, so i took a week to figure it out reading linux wireless implementation, everything was implemented and the only thing remain was enabling the flags, enabling made it work withouth issues so far.

**Comment by jeremyb31** [comment]
All I know is that the patch would likely have to be built on linux-next, https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git

**Comment by k3a** [comment]
hmm, are you sure software_iftypes should be set this way?
By grepping whole `drivers` kernel subdirectory I could find only these matches:
```
drivers/staging/rtl8723bs/os_dep/ioctl_cfg80211.c:      wiphy->software_iftypes |= BIT(NL80211_IFTYPE_MONITOR);
drivers/net/wireless/ath/ath10k/mac.c:          ar->hw->wiphy->software_iftypes |= BIT(NL80211_IFTYPE_AP_VLAN);
```

which suggests it may not be necessary.

I wanted to try the module without setting software_iftypes (keeping AP in features only) but during module load/unload my system froze. After reboot I also decided to upgrade the kernel and now I can't seem to be able to get it working both with and without software_iftypes. :D

I have also found an old repo from Jakub which doesn't look optimistic regarding AP mode ( https://github.com/kuba-moo/mt7601u/issues/4 ) so I don't know. I feel like it's not the right time to submit upstream unless we are certain it is enough to just set those flags this way and that the module is 100% stable.

**Comment by EduSSantoz** [comment]
youre right softwareif_types was not needed just added it to work on kernel 4.4 to be specific,
it refuses to enable the ap with just interface_modes flags.

its working great to me on a raspberry pi 2 with ubuntu server 18.04, using it as a AP with nfs, it has been working for more than a year withouth issues.

i have read what jakub written on his git, maybe a problem with enviroment, maybe some specific version or config of hostapd,
i don't know why is he having a hidden name on network, for the record here is what i use on hostap.conf:
`# the interface used by the AP
interface=wlan0
# "g" simply means 2.4GHz band
hw_mode=g
# the channel to use
channel=10
# limit the frequencies used to those allowed in the country
ieee80211d=1
# the country code
country_code=FR
# 802.11n support
ieee80211n=1
# QoS support, also required for full speed on 802.11n/ac/ax
wmm_enabled=1

# the name of the AP
ssid=somename
# 1=wpa, 2=wep, 3=both
auth_algs=1
# WPA2 only
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=somepassword`

it has been working since first time i build the driver,
for validation i have build it again with a git clone and it was working as expected.

can you provide me the log from your build? maybe i can help you to make it work.

there are other limitations on the device driver like ad-hoc and mesh network not beeing implemented
for sure it need a master of linux wirelless driver development.

that's all i use that for, create AP use MASKERADE to provide internet acess connect and get a network drive and internet from it.

i have tested it with various linux distros(arch,debian,fedora), and it worked.

also i'm with litle to no interest to mess with that anymore, the most important used, aspect of these cards is to get connected to, and the driver found on the almost every linux already provide it, having other features is always a nice touch to a device, but i think theres no need to put effert on it, since mediatek doesn't botthered to put it there.

**Comment by ScarletCarpet** [comment]
@EduSSantoz 
hi, i've built this driver for my raspberrypi 4B(kernel version is 5.10) and i turn on the AP by hostapd successfully.but i cannot connect to the AP using my iPhone. i can get the log such as this by hostapd:

`
Configuration file: /etc/hostapd/hostapd.conf
Using interface wlan1 with hwaddr 70:f1:1c:32:2b:6c and ssid "testap"
wlan1: interface state UNINITIALIZED->ENABLED
wlan1: AP-ENABLED 
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: authenticated
HT: Forty MHz Intolerant is set by STA 5a:00:7f:e0:56:60 in Association Request
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: associated (aid 1)
wlan1: AP-STA-CONNECTED 5a:00:7f:e0:56:60
wlan1: STA 5a:00:7f:e0:56:60 RADIUS: starting accounting session 2E4102DDB22E577C
wlan1: STA 5a:00:7f:e0:56:60 WPA: pairwise key handshake completed (RSN)
wlan1: AP-STA-DISCONNECTED 5a:00:7f:e0:56:60
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: disassociated
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: authenticated
HT: Forty MHz Intolerant is set by STA 5a:00:7f:e0:56:60 in Association Request
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: associated (aid 1)
wlan1: AP-STA-CONNECTED 5a:00:7f:e0:56:60
wlan1: STA 5a:00:7f:e0:56:60 RADIUS: starting accounting session A06A209FE0BD9D6D
wlan1: STA 5a:00:7f:e0:56:60 WPA: pairwise key handshake completed (RSN)
wlan1: AP-STA-DISCONNECTED 5a:00:7f:e0:56:60
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: disassociated
wlan1: STA 5a:00:7f:e0:56:60 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
`

it seems that all connection will be kick off. i have no idea about this. this is my hostapd.conf
`interface=wlan1
ssid=testap
hw_mode=g
channel=10
macaddr_acl=0
auth_algs=1
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
disassoc_low_ack=0
`

any help will be appreciated.

**Comment by ScarletCarpet** [comment]
> youre right softwareif_types was not needed just added it to work on kernel 4.4 to be specific,
> it refuses to enable the ap with just interface_modes flags.
> 
> its working great to me on a raspberry pi 2 with ubuntu server 18.04, using it as a AP with nfs, it has been working for more than a year withouth issues.
> 
> i have read what jakub written on his git, maybe a problem with enviroment, maybe some specific version or config of hostapd,
> i don't know why is he having a hidden name on network, for the record here is what i use on hostap.conf:
> `# the interface used by the AP
> interface=wlan0
> 
> # "g" simply means 2.4GHz band
> hw_mode=g
> 
> # the channel to use
> channel=10
> 
> # limit the frequencies used to those allowed in the country
> ieee80211d=1
> 
> # the country code
> country_code=FR
> 
> # 802.11n support
> ieee80211n=1
> 
> # QoS support, also required for full speed on 802.11n/ac/ax
> wmm_enabled=1
> 
> # the name of the AP
> ssid=somename
> 
> # 1=wpa, 2=wep, 3=both
> auth_algs=1
> 
> # WPA2 only
> wpa=2
> wpa_key_mgmt=WPA-PSK
> rsn_pairwise=CCMP
> wpa_passphrase=somepassword`
> 
> it has been working since first time i build the driver,
> for validation i have build it again with a git clone and it was working as expected.
> 
> can you provide me the log from your build? maybe i can help you to make it work.
> 
> there are other limitations on the device driver like ad-hoc and mesh network not beeing implemented
> for sure it need a master of linux wirelless driver development.
> 
> that's all i use that for, create AP use MASKERADE to provide internet acess connect and get a network drive and internet from it.
> 
> i have tested it with various linux distros(arch,debian,fedora), and it worked.
> 
> also i'm with litle to no interest to mess with that anymore, the most important used, aspect of these cards is to get connected to, and the driver found on the almost every linux already provide it, having other features is always a nice touch to a device, but i think theres no need to put effert on it, since mediatek doesn't botthered to put it there.

And now i found that ios device cannot connect it but Android or laptop works.

**Comment by EduSSantoz** [comment]
> > youre right softwareif_types was not needed just added it to work on kernel 4.4 to be specific,
> > it refuses to enable the ap with just interface_modes flags.
> > its working great to me on a raspberry pi 2 with ubuntu server 18.04, using it as a AP with nfs, it has been working for more than a year withouth issues.
> > i have read what jakub written on his git, maybe a problem with enviroment, maybe some specific version or config of hostapd,
> > i don't know why is he having a hidden name on network, for the record here is what i use on hostap.conf:
> > `# the interface used by the AP
> > interface=wlan0
> > # "g" simply means 2.4GHz band
> > hw_mode=g
> > # the channel to use
> > channel=10
> > # limit the frequencies used to those allowed in the country
> > ieee80211d=1
> > # the country code
> > country_code=FR
> > # 802.11n support
> > ieee80211n=1
> > # QoS support, also required for full speed on 802.11n/ac/ax
> > wmm_enabled=1
> > # the name of the AP
> > ssid=somename
> > # 1=wpa, 2=wep, 3=both
> > auth_algs=1
> > # WPA2 only
> > wpa=2
> > wpa_key_mgmt=WPA-PSK
> > rsn_pairwise=CCMP
> > wpa_passphrase=somepassword`
> > it has been working since first time i build the driver,
> > for validation i have build it again with a git clone and it was working as expected.
> > can you provide me the log from your build? maybe i can help you to make it work.
> > there are other limitations on the device driver like ad-hoc and mesh network not beeing implemented
> > for sure it need a master of linux wirelless driver development.
> > that's all i use that for, create AP use MASKERADE to provide internet acess connect and get a network drive and internet from it.
> > i have tested it with various linux distros(arch,debian,fedora), and it worked.
> > also i'm with litle to no interest to mess with that anymore, the most important used, aspect of these cards is to get connected to, and the driver found on the almost every linux already provide it, having other features is always a nice touch to a device, but i think theres no need to put effert on it, since mediatek doesn't botthered to put it there.
> 
> And now i found that ios device cannot connect it but Android or laptop works.

thats a known problem with hostapd, ios devices have problems to connect on it.

**Comment by ScarletCarpet** [comment]
> > > youre right softwareif_types was not needed just added it to work on kernel 4.4 to be specific,
> > > it refuses to enable the ap with just interface_modes flags.
> > > its working great to me on a raspberry pi 2 with ubuntu server 18.04, using it as a AP with nfs, it has been working for more than a year withouth issues.
> > > i have read what jakub written on his git, maybe a problem with enviroment, maybe some specific version or config of hostapd,
> > > i don't know why is he having a hidden name on network, for the record here is what i use on hostap.conf:
> > > `# the interface used by the AP
> > > interface=wlan0
> > > # "g" simply means 2.4GHz band
> > > hw_mode=g
> > > # the channel to use
> > > channel=10
> > > # limit the frequencies used to those allowed in the country
> > > ieee80211d=1
> > > # the country code
> > > country_code=FR
> > > # 802.11n support
> > > ieee80211n=1
> > > # QoS support, also required for full speed on 802.11n/ac/ax
> > > wmm_enabled=1
> > > # the name of the AP
> > > ssid=somename
> > > # 1=wpa, 2=wep, 3=both
> > > auth_algs=1
> > > # WPA2 only
> > > wpa=2
> > > wpa_key_mgmt=WPA-PSK
> > > rsn_pairwise=CCMP
> > > wpa_passphrase=somepassword`
> > > it has been working since first time i build the driver,
> > > for validation i have build it again with a git clone and it was working as expected.
> > > can you provide me the log from your build? maybe i can help you to make it work.
> > > there are other limitations on the device driver like ad-hoc and mesh network not beeing implemented
> > > for sure it need a master of linux wirelless driver development.
> > > that's all i use that for, create AP use MASKERADE to provide internet acess connect and get a network drive and internet from it.
> > > i have tested it with various linux distros(arch,debian,fedora), and it worked.
> > > also i'm with litle to no interest to mess with that anymore, the most important used, aspect of these cards is to get connected to, and the driver found on the almost every linux already provide it, having other features is always a nice touch to a device, but i think theres no need to put effert on it, since mediatek doesn't botthered to put it there.
> > 
> > 
> > And now i found that ios device cannot connect it but Android or laptop works.
> 
> thats a known problem with hostapd, ios devices have problems to connect on it.

Thanks for your reply at first!
And do u know there are any solution to fix it?

**Comment by EduSSantoz** [comment]
> Thanks for your reply at first!
> And do u know there are any solution to fix it?

no i can't help you, about that.

**Pull request merged**
